name: Build net48

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
env:
  PROJECT_NAME: TPShipToolkit
  SOLUTION_FILE: TPShipToolkit.sln
  TARGET_FRAMEWORK: net48

jobs:
  build:
    runs-on: windows-latest

    outputs:
      version: ${{ steps.tagStep.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Extract version from tag
        id: tagStep
        shell: bash
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Release
        run: msbuild ${{ env.SOLUTION_FILE }} `
                /p:Configuration=Release `
                /p:Platform="Any CPU" `
                /p:Version=$env:VERSION `
                /p:FileVersion=$env:VERSION `
                /p:AssemblyVersion=$env:VERSION

      - name: Prepare artifact
        shell: powershell
        run: |
          $out = "artifact/${{ env.PROJECT_NAME }}"
          New-Item -ItemType Directory -Force -Path $out

          Copy-Item `
            $env:PROJECT_NAME\bin\Release\$env:TARGET_FRAMEWORK\* `
            $out `
            -Recurse `
            -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-v${{ env.VERSION }}
          path: artifact

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-v${{ needs.build.outputs.version }}
          path: release

      - name: Zip release
        shell: powershell
        run: |
          Compress-Archive `
            -Path release\* `
            -DestinationPath ${{ env.PROJECT_NAME }}-v${{ needs.build.outputs.version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.PROJECT_NAME }} v${{ needs.build.outputs.version }}
          draft: true
          files: ${{ env.PROJECT_NAME }}-v${{ needs.build.outputs.version }}.zip
